"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { formatCurrency } from "@/lib/formatters/currency";

type Dashboard = {
  projects: { total: number; active: number; completed: number; delayed: number; items: Array<{ id: string; name: string; projectCode: string; client: string; location: string; manager: string; startDate: string; endDate: string; budget: number; expenses: number; progress: number; status: string; health: string }> };
  financial: { contractValue: number; budget: number; expenses: number; committedCost: number; remaining: number; budgetUsedPercentage: number };
  tasks: { total: number; completed: number; inProgress: number; overdue: number; blocked: number };
  operations: { materials: { total: number; lowStock: number; pendingDeliveries: number }; procurement: { pendingRequests: number; approvedOrders: number; pendingDeliveries: number }; issues: { open: number; critical: number } };
  deadlines: Array<{ title: string; dueDate: string; kind: string; projectId: string }>;
  overallProgress: number;
  recentActivities: Array<{ _id: string; action: string; entity: string; userName?: string; createdAt: string; projectId?: string }>;
};

const health = (value?: string) => value === "DELAYED" ? "bg-red-50 text-red-700" : value === "AT_RISK" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700";
const date = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(value));

export default function ConstructionDashboard({ userName = "there", onCreate }: { userName?: string; onCreate?: () => void }) {
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/dashboard", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error?.message || "Unable to load dashboard"); setData(result.data); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load dashboard")); }, []);
  if (error) return <section className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h2 className="font-semibold">Dashboard data is unavailable</h2><p className="mt-1 text-sm">{error}</p></section>;
  if (!data) return <DashboardSkeleton />;
  // Legacy records may predate the healthStatus field. Keep the presentation safe while
  // retaining the API's calculated value whenever it is available.
  data.projects.items.forEach((project) => { project.health ||= "ON_TRACK"; });
  const stats = [["Active projects", String(data.projects.active), "Live project portfolio"], ["Total project value", formatCurrency(data.financial.contractValue, true), "Signed contract value"], ["Total expenses", formatCurrency(data.financial.expenses, true), `${data.financial.budgetUsedPercentage}% of budget used`], ["Overall progress", `${data.overallProgress}%`, "Calculated from project progress"]];
  return <div className="space-y-6 text-slate-800">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">ConstructFlow · Construction ERP</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Hello, {userName.split(" ")[0]} <span aria-hidden>👋</span></h1><p className="mt-2 text-sm text-slate-500">Welcome back. Here’s what’s happening across your projects today.</p></div>{onCreate ? <button onClick={onCreate} className="rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-semibold text-slate-950 shadow-sm hover:bg-amber-400">+ Create Project</button> : <Link href="/projects/new" className="rounded-xl bg-amber-500 px-4 py-2.5 text-center text-sm font-semibold text-slate-950 shadow-sm hover:bg-amber-400">+ Create Project</Link>}</header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, note]) => <section key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-medium text-emerald-600">{note}</p></section>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.85fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Project progress</h2><p className="mt-1 text-xs text-slate-500">Progress reflects recorded project metrics.</p></div><Link href="/projects" className="text-sm font-semibold text-amber-700">View all</Link></div><div className="mt-5 space-y-5">{data.projects.items.map((project) => <Link key={project.id} href={`/projects/${project.id}/overview`} className="block rounded-xl p-2 transition hover:bg-slate-50"><div className="flex items-center justify-between gap-3 text-sm"><div><p className="font-semibold">{project.name}</p><p className="mt-1 text-xs text-slate-500">{project.projectCode} · {project.location}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${health(project.health)}`}>{project.health.replace("_", " ")}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{ width: `${project.progress}%` }} /></div><p className="mt-1.5 text-right text-xs font-semibold text-slate-600">{project.progress}% complete</p></Link>)}{data.projects.items.length === 0 && <p className="py-8 text-center text-sm text-slate-500">No accessible projects yet.</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Financial overview</h2><div className="mt-5 flex items-center gap-5"><div className="grid h-32 w-32 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#f59e0b ${data.financial.budgetUsedPercentage}%, #e2e8f0 0)` }}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><b>{data.financial.budgetUsedPercentage}%</b><span className="text-[10px] text-slate-500">budget used</span></div></div><div className="space-y-3 text-sm"><Metric label="Budget" value={formatCurrency(data.financial.budget, true)} /><Metric label="Actual expenses" value={formatCurrency(data.financial.expenses, true)} /><Metric label="Remaining" value={formatCurrency(data.financial.remaining, true)} /></div></div></section></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.85fr)]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between p-5"><div><h2 className="font-bold">Active projects</h2><p className="mt-1 text-xs text-slate-500">Budget, delivery and accountable manager.</p></div><Link href="/projects" className="text-sm font-semibold text-amber-700">View all</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-y border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">Project</th><th className="px-3 py-3 font-medium">Manager</th><th className="px-3 py-3 font-medium">Budget</th><th className="px-3 py-3 font-medium">Progress</th><th className="px-5 py-3 font-medium">Status</th></tr></thead><tbody>{data.projects.items.map((p) => <tr key={p.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><Link href={`/projects/${p.id}/overview`} className="font-semibold hover:text-amber-700">{p.name}</Link><p className="mt-1 text-xs text-slate-500">{p.client}</p></td><td className="px-3 py-4 text-slate-600">{p.manager}</td><td className="px-3 py-4 font-medium">{formatCurrency(p.budget, true)}</td><td className="px-3 py-4"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-amber-500" style={{ width: `${p.progress}%` }} /></div><span className="mt-1 block text-xs">{p.progress}%</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${health(p.health)}`}>{p.health.replace("_", " ")}</span></td></tr>)}</tbody></table></div></section>
    <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Upcoming deadlines</h2><div className="mt-4 space-y-4">{data.deadlines.map((item, index) => <Link key={`${item.title}-${index}`} href={`/projects/${item.projectId}/overview`} className="flex gap-3 rounded-xl p-2 hover:bg-slate-50"><div className="w-10 text-center"><b className="text-sm text-amber-700">{date(item.dueDate)}</b></div><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.kind}</p></div></Link>)}{data.deadlines.length === 0 && <p className="py-8 text-center text-sm text-slate-500">No upcoming deadlines recorded.</p>}</div></aside></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SmallStat title="Task overview" values={[["Total", data.tasks.total], ["Completed", data.tasks.completed], ["Overdue", data.tasks.overdue]]} /><SmallStat title="Materials inventory" values={[["Records", data.operations.materials.total], ["Low stock", data.operations.materials.lowStock], ["Pending", data.operations.materials.pendingDeliveries]]} /><SmallStat title="Procurement" values={[["Pending", data.operations.procurement.pendingRequests], ["Approved", data.operations.procurement.approvedOrders], ["Deliveries", data.operations.procurement.pendingDeliveries]]} /><SmallStat title="Project issues" values={[["Open", data.operations.issues.open], ["Critical", data.operations.issues.critical], ["Delayed", data.projects.delayed]]} /></div>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-slate-500">{label}</p><p className="mt-0.5 font-semibold">{value}</p></div>; }
function SmallStat({ title, values }: { title: string; values: [string, number][] }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-4 grid grid-cols-3 gap-2">{values.map(([label, value]) => <div key={label}><p className="text-lg font-bold">{value}</p><p className="text-[11px] text-slate-500">{label}</p></div>)}</div></section>; }
function DashboardSkeleton() { return <div className="animate-pulse space-y-6"><div className="h-20 rounded-2xl bg-slate-200" /><div className="grid gap-4 sm:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-36 rounded-2xl bg-slate-200" />)}</div><div className="grid gap-6 xl:grid-cols-2"><div className="h-96 rounded-2xl bg-slate-200" /><div className="h-96 rounded-2xl bg-slate-200" /></div></div>; }
