import Link from "next/link";

type PageKind = "platform" | "projects" | "about" | "demo";

const content: Record<PageKind, { eyebrow: string; title: string; summary: string; items: { title: string; body: string }[] }> = {
  platform: { eyebrow: "The Apex platform", title: "Clarity for every stage of development.", summary: "Apex Developments brings planning, delivery, financial control, and field coordination into one dependable workspace.", items: [{ title: "Portfolio oversight", body: "See risk, progress, and milestones across every active development." }, { title: "Cost control", body: "Track approved budgets, committed costs, and forecasts in real time." }, { title: "Field coordination", body: "Keep teams, tasks, inspections, and daily work aligned." }] },
  projects: { eyebrow: "Selected developments", title: "Places with purpose, built to last.", summary: "Our portfolio spans residential, commercial, and infrastructure projects designed around lasting value and better communities.", items: [{ title: "Westfield Tower A", body: "A high-rise residential community advancing through its structural phase." }, { title: "Harbor Bridge Renewal", body: "A resilient infrastructure upgrade reconnecting a growing waterfront district." }, { title: "Greenfield Logistics Hub", body: "A future-ready industrial campus built for efficient regional distribution." }] },
  about: { eyebrow: "About Apex", title: "Development with a higher standard.", summary: "Apex Developments pairs rigorous project execution with thoughtful design to create spaces that perform for generations.", items: [{ title: "Our approach", body: "We combine local insight, disciplined delivery, and clear communication from first concept to handover." }, { title: "Our people", body: "Our teams bring development, construction, commercial, and operational expertise." }, { title: "Our commitment", body: "We build enduring value for clients, communities, and the people who use our places every day." }] },
  demo: { eyebrow: "Product walkthrough", title: "See Apex in action.", summary: "Explore how a connected view of projects, costs, crews, and delivery milestones helps your team make better decisions every day.", items: [{ title: "1. See the full picture", body: "Start with a live portfolio view to identify what needs attention." }, { title: "2. Coordinate the work", body: "Use projects, tasks, and schedules to keep every delivery team aligned." }, { title: "3. Act with confidence", body: "Use timely budget and progress signals to resolve issues before they grow." }] },
};

export default function MarketingPage({ kind }: { kind: PageKind }) {
  const page = content[kind];
  const nav = [["Platform", "/platform"], ["Projects", "/projects"], ["About", "/about"]];
  return <main style={{ minHeight: "100vh", background: "#0F1115", color: "#E4E5E7", fontFamily: "Work Sans, sans-serif" }}>
    <header style={{ padding: "22px 48px", borderBottom: "1px solid #3F434C", display: "flex", justifyContent: "space-between", alignItems: "center" }}><Link href="/" style={{ color: "#E4E5E7", fontFamily: "Roboto Slab, serif", fontWeight: 700, textDecoration: "none" }}>Apex <span style={{ color: "#C9A15A" }}>Developments</span></Link><nav style={{ display: "flex", gap: 24 }}>{nav.map(([label, href]) => <Link key={href} href={href} style={{ color: "rgba(228,229,231,0.65)", fontSize: 13, textDecoration: "none" }}>{label}</Link>)}</nav></header>
    <section style={{ maxWidth: 1120, margin: "0 auto", padding: "112px 48px 80px" }}><p style={{ color: "#C9A15A", fontFamily: "JetBrains Mono, monospace", fontSize: 11, letterSpacing: ".16em", textTransform: "uppercase" }}>{page.eyebrow}</p><h1 style={{ maxWidth: 760, margin: "20px 0", fontFamily: "Roboto Slab, serif", fontSize: 52, lineHeight: 1.08, letterSpacing: "-.03em" }}>{page.title}</h1><p style={{ maxWidth: 650, color: "rgba(228,229,231,.65)", fontSize: 18, lineHeight: 1.7 }}>{page.summary}</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 18, marginTop: 64 }}>{page.items.map((item) => <article key={item.title} style={{ background: "#16181D", border: "1px solid #3F434C", borderRadius: 12, padding: 28 }}><div style={{ width: 28, height: 3, background: "#C9A15A", marginBottom: 24 }} /><h2 style={{ fontFamily: "Roboto Slab, serif", fontSize: 21 }}>{item.title}</h2><p style={{ color: "rgba(228,229,231,.6)", lineHeight: 1.7 }}>{item.body}</p></article>)}</div>{kind === "demo" && <Link href="/" style={{ display: "inline-block", marginTop: 48, background: "#C9A15A", borderRadius: 6, color: "#0F1115", fontWeight: 700, padding: "13px 24px", textDecoration: "none" }}>Open Dashboard</Link>}</section>
  </main>;
}
